FROM php:8.2-apache 

# Install necessary system packages 
RUN apt-get update && apt-get install -y \
    libzip-dev \
    libonig-dev \
    unzip \
    git \
    && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo pdo_mysql mysqli

COPY ./app/php-app/ /var/www/html/

# Expose the port 
EXPOSE 80